name: Cenit test
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  build-container:
    name: Integration test for Cenit
    runs-on: ubuntu-latest

    steps:
      - name: Installing Cenit dependencies
        run: sudo apt update
      - run: sudo apt upgrade -y
      - run: sudo apt install -y zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev libffi-dev imagemagick libmagickwand-dev -y
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: 3.6

      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.1.0

      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.5
          bundler-cache: true
      - run: bundle exec rake assets:precompile
      - run: bundle exec rspec spec
        env:
         SKIP_RABBIT_MQ: true
